version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: wehosst
    networks:
      - netwokname
networks:
  netwokname: